/**
 * Path tương đối sau tiền tố `/api` (Nest `setGlobalPrefix('api')`).
 * Luôn bọc bằng `apiUrl(...)` khi gọi fetch.
 */
export const apiPaths = {
	/** Cấu hình website (public, không cần JWT) */
	globalConfig: '/global-config',
	auth: {
		login: '/auth/login',
		refresh: '/auth/refresh',
		logout: '/auth/logout',
		dashboard: '/auth/dashboard',
		mePassword: '/auth/me/password',
		forgotPassword: '/auth/forgot-password',
		resetPassword: '/auth/reset-password',
		totpLogin: '/auth/totp/login',
		totpEnrollStart: '/auth/totp/enroll/start',
		totpEnrollVerify: '/auth/totp/enroll/verify',
		totpDisable: '/auth/totp/disable',
	},
	admin: {
		internalUsers: '/admin/internal-users',
		customers: '/admin/customers',
		customersBulkDelete: '/admin/customers/bulk-delete',
		user: (id: string) => `/admin/users/${id}`,
		/** Một bản ghi cấu hình website (GET + PATCH) */
		globalConfig: '/admin/global-config',
		orders: '/admin/orders',
		dashboardOverview: '/admin/dashboard/overview',
		dashboardAnalytics: '/admin/dashboard/analytics',
		dashboardInventory: '/admin/dashboard/inventory',
		dashboardOperations: '/admin/dashboard/operations',
		dashboardEngagement: '/admin/dashboard/engagement',
	},
	/** Public + admin (JWT cho POST/PATCH/DELETE) */
	products: '/products',
	product: (id: string) => `/products/${id}`,
	productPublish: (id: string) => `/products/${id}/publish`,
	productArchive: (id: string) => `/products/${id}/archive`,
	productCategories: '/product-categories',
	productCategory: (id: string) => `/product-categories/${id}`,
	productCategoryPublish: (id: string) => `/product-categories/${id}/publish`,
	productCategoryArchive: (id: string) => `/product-categories/${id}/archive`,
	productMaterials: '/product-materials',
	productMaterial: (id: string) => `/product-materials/${id}`,
	productMaterialsBulkDelete: '/product-materials/bulk-delete',
	articles: '/articles',
	article: (id: string) => `/articles/${id}`,
	articleBySlug: (slug: string) => `/articles/slug/${encodeURIComponent(slug)}`,
	articlePublish: (id: string) => `/articles/${id}/publish`,
	articleArchive: (id: string) => `/articles/${id}/archive`,
	customerFeedbacks: '/customer-feedbacks',
	customerFeedback: (id: string) => `/customer-feedbacks/${id}`,
	customerFeedbackBySlug: (slug: string) => `/customer-feedbacks/slug/${encodeURIComponent(slug)}`,
	customerFeedbackPublish: (id: string) => `/customer-feedbacks/${id}/publish`,
	customerFeedbackArchive: (id: string) => `/customer-feedbacks/${id}/archive`,
	contactInquiries: '/contact-inquiries',
	contactInquiriesSummary: '/contact-inquiries/summary',
	contactInquiry: (id: string) => `/contact-inquiries/${id}`,
	contactInquiryRead: (id: string) => `/contact-inquiries/${id}/read`,
	contactInquiryArchive: (id: string) => `/contact-inquiries/${id}/archive`,
	staticPages: '/static-pages',
	staticPage: (id: string) => `/static-pages/${id}`,
	staticPageBySlug: (slug: string) => `/static-pages/slug/${encodeURIComponent(slug)}`,
	staticPagePublish: (id: string) => `/static-pages/${id}/publish`,
	staticPageArchive: (id: string) => `/static-pages/${id}/archive`,
	campaigns: '/campaigns',
	campaign: (id: string) => `/campaigns/${id}`,
	campaignPublish: (id: string) => `/campaigns/${id}/publish`,
	campaignArchive: (id: string) => `/campaigns/${id}/archive`,
	campaignActiveList: '/campaigns/active',
	promotionDiscounts: '/promotion-discounts',
	promotionDiscount: (id: string) => `/promotion-discounts/${id}`,
	promotionDiscountPublish: (id: string) => `/promotion-discounts/${id}/publish`,
	promotionDiscountArchive: (id: string) => `/promotion-discounts/${id}/archive`,
	upload: {
		productImage: '/upload/product-image',
	},
	inventory: {
		adjustProduct: (id: string) => `/inventory/products/${id}`,
		transactions: '/inventory/transactions',
	},
} as const;
